### ISSUE TITLE
Why are `cloud_provider.properties.[registry|blobstore|nats]` required?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-micro-cli#8]
```yaml
cloud_provider:
  template:
    name: cpi
    release: bosh-aws-cpi
  ssh_tunnel:
    host: 10.10.0.4
    port: 22
    user: vcap
    private_key: /home/ubuntu/.ssh/sw-bosh-us-east-1.pem
  properties:
    aws: ...
    registry:
      username: admin
      password: admin
      port: 6901
      host: localhost
    blobstore:
      provider: local
      path: /var/vcap/micro_bosh/data/cache
    nats:
      address: 127.0.0.1
      password: nats
```

When trying to deploy a simple redis VM - it seems odd that I was forced to specify `cloud_provider.properties.[registry|blobstore|nats]` - these seem like job properties that would be enforced by bosh's own release - not by the bosh-micro-cli.
